name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install the package and dependencies
        run: python -m pip install -U pip && pip install build flake8 pytest && pip install -e .[caption]
      - name: pytest
        run: pytest
      - name: flake8
        run: flake8
      - name: Build
        run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
