name: Test

on:
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install the package and dependencies
        run: python -m pip install -U pip && pip install flake8 pytest && pip install -e .[caption]
      - name: pytest
        run: pytest
      - name: Flake8
        run: flake8
  build-me-read:
    name: Build-Me-Read
    runs-on: ubuntu-latest
    permissions: read-all
